default_settings: null
behaviors:
  DodgeBall:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 1.0e-05
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    checkpoint_interval: 100000
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
      gail:
        gamma: 0.99
        strength: 0.1
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
        learning_rate: 0.0003
        encoding_size: null
        use_actions: false
        use_vail: false
        demo_path: Demos/ExplorationDemo
    init_path: null
    keep_checkpoints: 5
    even_checkpoints: false
    max_steps: 200000000
    time_horizon: 1000
    summary_freq: 50000
    threaded: false
    self_play:
      save_steps: 20000
      team_change: 100000
      swap_steps: 80000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
    behavioral_cloning:
      demo_path: Demos/ExplorationDemo
      steps: 0
      strength: 0.2
      samples_per_update: 0
      num_epoch: null
      batch_size: null
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  num_areas: 1
  timeout_wait: 60
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 1.0
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
checkpoint_settings:
  run_id: Dodgeball_Imitation_Exploration
  initialize_from: null
  load_model: false
  resume: true
  force: false
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false
